name: Deploy Astro site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  BUILD_PATH: "./astro"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.BUILD_PATH }}
      - name: Build with Astro
        run: |
          yarn astro build
        working-directory: ${{ env.BUILD_PATH }}
