name: Trigger Astro build on server
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [custom_event]
jobs:
  build:
    name: Run remote SSH command
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            ls
